name: Laravel CI/CD with Self-Hosted Runner

on:
  push:
    branches:
      - main  # Runs when code is pushed to the main branch

jobs:
  deploy:
    runs-on: self-hosted  # Uses the GitHub self-hosted runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Navigate to Laravel Project and Deploy
        run: |
          cd /var/www/html/laravel10
          git config --global --add safe.directory /var/www/html/laravel10
          git add .
          git commit -m "serversidechanges" || echo "No changes to commit"
          git pull origin main
          pm2 restart 13
